/*
海洋垃圾项目 - 共享脚本
Marine Debris Project - Shared Script

此文件包含项目中多个页面共享的数据和功能。
This file contains data and functions shared across multiple pages in the project.

主要内容：
- 多语言翻译数据 (translations)
- 游戏数据 (debrisPieces, chartData)
- 地图区域数据 (regionMapData)
- 本地化标签 (localizedLabels)
- 工具函数 (translatePage, getLocalizedLabel, etc.)

Main contents:
- Multilingual translation data
- Game data (debrisPieces, chartData)
- Map region data (regionMapData)
- Localized labels
- Utility functions
*/

/**
 * 多语言翻译数据
 * Multilingual translation data
 * 支持日语、英语和中文
 * Supports Japanese, English, and Chinese
 */
const translations = {
  // 三种语言必须保持相同键名；HTML 的 data-i18n 与页面脚本都依赖这些键。
  ja: {
    heroEyebrow: '日本周辺の海を守ろう',
    languageLabel: '言語',
    heroTitle: '海洋ゴミが日本の海洋環境に与える影響',
    heroSubtitle: '浮遊プラスチック、漁具、ペットボトルなど、日本沿岸で増え続けるゴミと海の生きものへの負担を、学びながら体験します。',
    startButton: '体験を開始する',
    introTitle: 'インタラクティブに日本近海の海ごみ問題を理解する',
    introText: '実際の映像、清掃シミュレーション、データ可視化、地域マップを通じて、海ごみの影響を観察・比較できます。',
    introKicker: '学習入口',
    introMetricOneLabel: '主な流入源',
    introMetricOneText: '陸域からの流入と推定される割合',
    introMetricTwoLabel: '主要カテゴリ',
    introMetricTwoText: 'ボトル、漁具、発泡材、缶・瓶など',
    introMetricThreeLabel: '学習方式',
    introMetricThreeText: '映像、ゲーム、シミュレーション、データ、地図、行動',
    introModuleVisual: '映像観察',
    introModuleVisualTitle: 'まず問題を見る',
    introModuleSim: '参加変化',
    introModuleSimTitle: '次に回復を試す',
    introModuleData: 'データ図表',
    introModuleDataTitle: '最後に証拠を比較',
    homeTabsTitle: '学習モジュール',
    homeTabsDescription: '下のタブでテーマ別ページを切り替えます。',
    tabIntro: '概要',
    tabEmpathy: '映像',
    tabGame: '清掃ゲーム',
    tabCleanup: '参加変化',
    tabChart: 'データ',
    tabMap: '地図',
    tabImpact: '影響',
    tabActions: '行動',
    gameKicker: '清掃ゲーム',
    gameTitle: '海ごみ清掃ゲーム',
    gameDescription: 'ウミガメの診断から始まり、汚染された対象は海面のごみをすべて回収した時だけ元の姿に戻ります。その後、未体験の海域へランダムに進みます。',
    gameHeroLabel: 'インタラクティブ任務',
    gameHeroValue: '観察 · 清掃 · 探索',
    gameHeroNote: '汚染された対象を観察し、すべてのごみを回収して元の健康な姿へ戻します。',
    gameInstructions: '海面のごみをすべて取り除き、最初のウミガメを助けてください。',
    recycleBoat: '資源回収ボート',
    trashBoat: '一般ゴミボート',
    debrisPlastic: 'プラスチックボトル',
    debrisFishing: '漁具片',
    debrisOrganic: '海藻混入ゴミ',
    debrisOther: '発泡スチロール',
    chartTitle: '日本周辺海域のごみ量：種類別に見る影響',
    chartDescription: '環境省の年度推計資料をもとに、プラスチックごみ、道路由来の粉じん、衣類の繊維、洗剤類など、量として把握できる発生源を並べて比較します。',
    chartKicker: 'データ証拠',
    chartMethodLabel: '読み方',
    chartMethodValue: '日本周辺・毎年どれくらい',
    chartMethodNote: '複雑な推計値を、読みやすい量の表現に置き換えています。',
    chartInputLabel: '年間総量',
    chartInputValue: '年間 約1.6万-3.1万トン',
    chartInputNote: '環境省が発生源・品目別に推計した、日本から海へ流出するプラスチックごみ量です。',
    chartPlasticLabel: '大きなプラスチックごみ',
    chartPlasticValue: '年間 約1,300-8,600トン',
    chartPlasticNote: '投げ捨てごみや海岸ごみなど、目に見えて拾えるプラスチックごみです。',
    chartLandLabel: 'マイクロプラスチック粉じん',
    chartLandValue: '年間 約1.4万-2.0万トン',
    chartLandNote: 'タイヤ、道路標示材、塗料、人工芝などが摩耗して細かな粒になり、雨水とともに水域へ流れます。',
    chartRiverLabel: '衣類繊維と洗剤類',
    chartRiverValue: '繊維 約230-240トン',
    chartRiverNote: '洗濯で出る繊維や、洗剤類に含まれる香りカプセルも、汚水経由で海へ届く可能性があります。',
    chartCompositionLabel: '種類別比較',
    chartCompositionTitle: 'どのごみが日本周辺の海へ流れているか',
    chartHighlightOne: '最大級の項目はタイヤや道路標示材などの摩耗粉じん',
    chartHighlightTwo: '衣類繊維は毎日の洗濯から生まれます',
    chartHighlightThree: '洗剤類の香りカプセルは少量でも暮らしに近い発生源です',
    chartVolumeTotalLabel: '日本の海洋プラスチックごみ流出総量',
    chartVolumeNote: '大きなプラスチック、マイクロプラスチック、衣類繊維、洗剤類、道路・タイヤ由来の粉じんなど、推計できる項目を含みます。',
    chartDetailsKicker: '出典メモ',
    chartDetailsTitle: 'データの出典と読み方',
    chartLegendRecycle: '遮断・対策界面',
    chartLegendTrash: 'ごみ量が多い界面',
    chartSourceMOEEstimate: '環境省 量的資料',
    chartSourceMOE2025: '環境省 FY2025',
    chartSourceMOE2025Short: '環境省 FY2025',
    chartSourceMOESurvey: '海洋ごみ実態把握調査',
    chartSourceNote: '読み方',
    chartSourceMOEEstimateTitle: '海洋ごみの量的把握方法',
    chartSourceMOEEstimateText: '環境省が発生源・品目別に海洋への流出量を推計する口径の確認に使用。',
    chartSourceMOE2025Title: '令和7年度検討結果',
    chartSourceMOE2025Text: 'プラスチックごみ総量、マイクロプラスチック、繊維、洗剤類などの年間レンジに使用。',
    chartSourceMOESurveyTitle: '調査報告書インデックス',
    chartSourceMOESurveyText: '日本の海洋ごみ調査、漂着ごみ、漂流ごみ、海底ごみ関連の年度報告を確認できます。',
    chartSourceNoteTitle: '数値は暫定推計です',
    chartSourceNoteText: '数量感と種類の違いを理解するための値で、海の中のすべてのごみを一つずつ数えたものではありません。',
    mapKicker: '沿岸インパクト',
    mapTitle: '日本沿岸のごみ影響を地図で見る',
    mapDescription: '環境省や研究資料の信頼できる量感を、日本沿岸の代表的な場所に置いて読みます。どこが入口になり、どこがたまりやすく、どこで漁業・サンゴ・海鳥への影響が出やすいかを確認できます。',
    mapHeroLabel: '地図の読み方',
    mapHeroValue: '点位 · 量感 · 影響',
    mapHeroNote: '地図上の点を押すと、沿岸環境ごとのごみの発生源、量の目安、生態影響を確認できます。',
    mapReadLabel: '読み方',
    mapReadTitle: '点が大きいほど、その場所で注目すべき影響が大きいことを示します',
    mapReadText: '点は港湾ごとの精密な総量ではなく、公式の総量・回収量・調査知見を、わかりやすい沿岸影響として整理したものです。',
    mapLow: '低',
    mapMedium: '中',
    mapHigh: '高',
    mapWeightLow: '低い影響',
    mapWeightMedium: '中程度の影響',
    mapWeightHigh: '高い影響',
    mapFilterAll: 'すべて',
    mapNoData: 'この条件に一致する地域データはありません。',
    mapAmountLabel: '量の目安',
    mapImpactLabel: '主な影響',
    mapSourceOne: '環境省 FY2025',
    mapSourceOneTitle: '日本の海洋プラスチックごみ流出量の推計',
    mapSourceTwo: '環境省 調査索引',
    mapSourceTwoTitle: '海洋ごみ実態把握調査',
    impactTitle: '海洋ごみは遠くに漂うだけの問題ではない',
    impactDescription: '海面、海底、食物連鎖、沿岸コミュニティへ同時に入り込みます。影響の流れを理解すると、清掃と削減の優先順位が見えてきます。',
    impactKicker: '生態影響',
    impactSignalLabel: 'リスクサイン',
    impactSignalValue: '絡まり・誤食・マイクロプラスチック',
    impactSignalNote: '一つのごみが長期的な生態ストレスに変わる',
    impactExploreButton: '影響の流れを見る',
    impactChainKicker: '影響経路',
    impactChainTitle: '一つのごみが、どうシステム全体の圧力になるか',
    impactChainDescription: '経路を選び、海洋ごみが一度の接触から生きもの、すみか、食物連鎖へどう伝わるかを見てください。',
    impactPathOneTitle: '誤食と栄養損失',
    impactPathOneText: '透明なプラスチック、キャップ、発泡材は魚・海鳥・ウミガメに餌と間違われ、消化を妨げます。',
    impactPathOneFlow: '餌と誤認 → 誤食 → 栄養不足',
    impactPathTwoTitle: '漁具の絡まりとゴーストフィッシング',
    impactPathTwoText: '捨てられた網やロープは生きものを絡め続け、海草場や岩礁の構造にも傷を残します。',
    impactPathTwoFlow: '漂流 → 絡まり → ゴーストフィッシング',
    impactPathThreeTitle: 'マイクロプラスチックの食物連鎖',
    impactPathThreeText: '細かく砕けたプラスチックは回収が難しく、プランクトンや小魚を通じて食物連鎖へ入ります。',
    impactPathThreeFlow: '細片化 → 小さな生物が摂取 → 食物連鎖',
    impactDetailLabel: '現在の影響経路',
    impactDetailFlowLabel: '広がる過程',
    impactSystemKicker: '影響範囲',
    impactSystemTitle: '影響は海岸線で止まらない',
    impactSystemDescription: '同じごみが漂流、沈降、細片化し、沿岸環境と地域の暮らしへ届きます。',
    impactInsightOneValue: '海面',
    impactInsightOneText: '漂流ごみは港湾、河口、潮流の交差点に集まり、景観・航行・近岸生物へ影響します。',
    impactInsightTwoValue: '海底',
    impactInsightTwoText: '沈んだごみは底生生物のすみかを覆い、泥や岩礁の環境を変化させます。',
    impactInsightThreeValue: '地域',
    impactInsightThreeText: '清掃費、漁獲の品質、観光体験に影響し、環境問題は生活へ戻ってきます。',
    impactLensKicker: 'ビジュアル比較',
    impactLensTitle: '同じ海域、二つの未来',
    impactLensDescription: '視点を切り替え、ごみが蓄積する状態と生態系が回復した状態を比べます。',
    impactLensCurrent: '現在の圧力',
    impactLensRestored: '回復した海',
    impactLensCurrentCaption: 'ごみは海面と水中で同時に蓄積し、見える場所の外にも生態圧力を広げます。',
    impactLensRestoredCaption: '流入を減らし、回収を続けることで、水中のすみかと生きものの動きが戻り始めます。',
    impactLensCurrentAlt: 'ごみの圧力を受ける日本沿岸',
    impactLensRestoredAlt: '回復した透明な日本沿岸の海',
    impactNextKicker: '次のステップ',
    impactNextTitle: '影響を見たら、理解を行動に変える',
    impactNextDescription: '使い捨て用品を減らすこと、正しく分別すること、沿岸清掃に参加することが、次に海へ入るごみを減らします。',
    impactNextButton: '行動計画を見る',
    impactNorthTitle: '北日本',
    impactNorthText: 'プラスチック片が流氷とともに漂着し、海鳥やアザラシに危険をもたらしています。',
    impactWestTitle: '西日本',
    impactWestText: '九州や瀬戸内海では、漁具やビニールが漁業資源に悪影響を与えています。',
    impactSouthTitle: '南西諸島',
    impactSouthText: '珊瑚礁周辺でのプラスチック破片やマイクロプラスチックが生態系ストレスを高めています。',
    actionsKicker: 'アクションプラン',
    actionsTitle: '海を守る行動を毎日の小さな習慣にする',
    actionsDescription: '効果のある行動は一度きりの熱意ではなく、発生抑制、正しい回収、地域参加、継続的な記録を組み合わせることです。',
    actionsImpactLabel: '優先順位',
    actionsImpactValue: '減らす・流さない・記録する',
    actionsImpactNote: '発生源で減らすことは、後から拾うより効果的です。',
    actionOneTitle: '使い捨てプラスチックを減らす',
    actionOne: 'マイボトル、バッグ、カトラリーを持ち歩き、河川へ入りやすい軽量包装を減らします。',
    actionTwoTitle: 'ごみを回収システムに戻す',
    actionTwo: 'ボトル、缶、ガラス、発泡材は空にして圧縮・分別し、海岸ではなく回収ルートへ戻します。',
    actionThreeTitle: '清掃に参加して記録する',
    actionThree: '海岸や河川の清掃に参加し、よく見つかるごみの種類を記録して発生源の把握に役立てます。',
    actionFourTitle: '身近な選択を変える',
    actionFour: '学校、サークル、店舗で給水スポット、分別表示、再利用の仕組みを提案します。',
    actionsCommunityKicker: 'チームで広げる',
    actionsCommunityTitle: '個人の習慣から地域の仕組みへ',
    actionsCommunityText: '活動を企画するなら、拾った量だけでなく、ごみの種類、場所、天候、参加人数を残すことが重要です。次の行動がより正確になります。',
    footerText: 'copyright © 2026 KCGI group 22 All rights reserved.',
    chartCanvasTitle: '日本周辺海域のごみ量',
    regionValueSuffix: 'の沿岸影響指数です。',
    instructionCorrect: '✅ {item} — スコア +{score}。合計スコア: {totalScore}。',
    instructionWrong: '❌ {item} ではありません。もう一度試してみてください。',
    instructionUnknown: '不明なゴミです。正しい場所に戻してください。',
    empathyKicker: '映像で見る',
    empathyTitle: '日本沿岸の海洋ごみを映像で見る',
    empathyDescription: '動画と日本沿岸の画像を通じて、抽象的な海洋ごみ問題を、見て感じて話し合える現実の場面に変えます。',
    empathyHeroLabel: '見るポイント',
    empathyHeroValue: '経路 · 生きもの · 海岸',
    empathyHeroNote: 'ごみが海へ入る流れを見てから、沿岸風景、生態、人の活動との関係を確認します。',
    videoKicker: 'テーマ動画',
    videoTitle: 'プラスチックはどのように海の生態系へ入るのか',
    videoDescription: '日常のプラスチックごみが河川、湾、海洋生物へ移動する流れを短い動画で確認します。',
    imageCaption1: '北海道の漁村と漂着ゴミ',
    imageCaption2: '沖縄近海の珊瑚と海の生き物',
    imageCaption3: '地域漁業と海洋環境のつながり',
    officialImageNote: '画像出典：環境省（公開ページ）',
    impactInteractiveTitle: '自分の手で参加し、変化を観察する',
    impactInteractiveDescription: '清掃ごとに水質と生態が変化し、「手で修復する」体験ができます。',
    cleanupKicker: '参加して変化を見る',
    cleanupHeroLabel: 'シミュレーション',
    cleanupHeroValue: '現在 · 部分 · 完全',
    cleanupHeroNote: '清掃の段階を切り替え、水質、ごみ量、海の生きものの状態がどう変わるか観察します。',
    beforeLabel: '清掃前',
    afterLabel: '清掃後',
    cleanupFieldKicker: '現地観察メモ',
    cleanupFieldTitle: '清掃は写真だけでなく、確認できる記録も変えます',
    cleanupFieldPeople: '人のボランティアが参加',
    cleanupFieldWeight: 'の漂着ごみを回収',
    cleanupFieldSteps: '段階を継続して観察',
    cleanupFieldText: '海岸のごみ密度、清掃中の分別回収、清掃後に細かなプラスチックや漁網が残っていないかを観察します。',
    cleanupFieldSource: '資料：沖縄県 2024年照間海岸清掃成果',
    cleanupEvidenceKicker: '日本の現地写真',
    cleanupEvidenceTitle: '汚染の発見から、清掃、回復した海岸まで',
    cleanupEvidenceNote: '以下は環境省と沖縄県が公開した実際の現場写真です。清掃段階の説明に使用しており、同じ場所の連続比較ではありません。',
    impactPhoto1: '清掃前：ごみが海岸植物に絡んだ状態',
    impactPhoto2: '部分清掃：ボランティアが分別・回収中',
    impactPhoto3: '完全清掃：海岸線がきれいな状態に回復',
    impactPhotoSourceOne: '出典：環境省 関東地方環境事務所',
    impactPhotoSourceTwo: '出典：沖縄県 照間海岸清掃成果',
    impactPhotoSourceThree: '出典：沖縄県が公開した清掃後写真',
    cleanupImageNote: '写真の著作権は各公開機関に帰属します。写真下の出典から元ページを確認できます。',
    gameDashboardKicker: '海洋診断シート',
    gameDashboardTitle: '清掃進捗パネル',
    gamePatientNameLabel: '対象',
    gamePatientName: 'ウミガメ',
    gamePatientHabitatLabel: '発生海域',
    gamePatientHabitat: '日本周辺海域',
    gamePollutionLabel: '主な汚染',
    gameTreatmentLabel: '治療内容',
    gameDebrisCountLabel: '海面のごみ',
    gameHealthLabel: '環境健康度',
    gameScoreLabel: 'スコア',
    gameCorrectLabel: '正解数',
    gameRemainingLabel: '残りごみ',
    gameAccuracyLabel: '正答率',
    gameProgressText: '完了レベル: {cleaned} / {total}',
    gameRoundText: '第 {current} 海域 / 全 {total} 海域',
    gameRemainingLevelsText: '残り {remaining} 海域を診断',
    gameAllStationsComplete: 'すべての診断が完了',
    gameDebrisCountText: '{cleaned} / {total} 個を回収',
    gameLevelInstruction: '{sea}の{animal}を診断します。主な汚染は「{pollution}」。海面にある{total}個のごみをすべて回収してください。',
    gameLevelProgressMessage: '{cleaned} / {total}個を回収しました。残りのごみも取り除くと、{treatment}が完了します。',
    gameLevelCompleteMessage: '{animal}の治療が完了しました。次は未体験の海域からランダムに選ばれます。',
    gameAllCompleteMessage: '5つの海域の診断が完了しました。すべての生きものと環境が回復しています。',
    gameCleanedMessage: 'ごみを1つ回収しました。水が少し明るくなり、ウミガメの健康度も上がっています。',
    gameCompleteMessage: '治療成功です。海面のごみをすべて回収し、ウミガメの健康度が100%に戻りました。',
    gameAnimalAlt: '海洋ごみの影響を受ける{animal}',
    gamePollutedAnimalAlt: '海洋ごみに汚染された{animal}',
    gameRestoredAnimalAlt: '清掃後に回復した{animal}',
    gameDebrisAlt: '海面に浮かぶ{debris}',
    gameDebrisButtonLabel: '{debris}を回収する',
    gameTurtleAlt: '海洋ごみの影響を受けるウミガメ',
    gameTrashPlasticAlt: '漂流するプラスチックごみ',
    gameTrashBottleAlt: '海に浮かぶプラスチックボトル',
    gameTrashNetAlt: '廃棄された漁網',
    randomNextLevelButton: '次の海域をランダムに選ぶ',
    nextLevelLockedButton: '清掃後に次の海域へ',
    restartSessionButton: 'ウミガメからもう一度始める',
    restartGameButton: 'この海域をやり直す',
    gameStep1: '{animal}の発生海域は{sea}です。',
    gameStep2: '主な汚染「{pollution}」を含む{total}個のごみを回収します。',
    gameStep3: '清掃後は、まだ体験していない海域へランダムに進みます。',
    statusText: '水質回復: {percent}%',
    simulationTitle: '影響シミュレーション',
    simulationCurrent: '現在の状態',
    simulationPartial: '部分的な清掃',
    simulationFull: '完全な清掃',
    simulationImageAltCurrent: 'ごみで汚れた海と漂流プラスチック',
    simulationImageAltPartial: '部分的に清掃された海岸、まだ残るゴミ',
    simulationImageAltFull: '澄んだ海水と健康な海洋生物',
    simulationImageCaptionCurrent: '漂うごみで汚れた海水',
    simulationImageCaptionPartial: '部分清掃後でも続く努力が必要',
    simulationImageCaptionFull: '完全清掃後の健康な海',
    debrisLevelLabel: 'ごみ量',
    marineLifeLabel: '海の生きもの',
    waterColorLabel: '海水',
    marineLifePoor: '弱っている',
    marineLifeModerate: '回復中',
    marineLifeHealthy: '良好',
    waterCloudy: '濁っている',
    waterModerate: '少し澄んでいる',
    waterClear: '澄んでいる'
  },
  zh: {
    heroEyebrow: '守护日本周边海洋',
    languageLabel: '语言',
    heroTitle: '海洋垃圾对日本沿海环境的影响',
    heroSubtitle: '通过浮游塑料、渔具、饮料瓶等实例，体验不断增加的垃圾对海洋生命的负担。',
    startButton: '开始体验',
    introTitle: '用互动方式理解日本近海垃圾问题',
    introText: '从真实影像、清理模拟、数据图表到区域地图，这个页面把“垃圾如何影响海洋”拆成可以观察、点击和比较的学习路径。',
    introKicker: '学习入口',
    introMetricOneLabel: '主要来源',
    introMetricOneText: '来自陆源输入的估计占比',
    introMetricTwoLabel: '高频类型',
    introMetricTwoText: '塑料瓶、渔具、泡沫、瓶罐等重点类别',
    introMetricThreeLabel: '学习方式',
    introMetricThreeText: '影像、游戏、模拟、数据、地图和行动模块',
    introModuleVisual: '影像观察',
    introModuleVisualTitle: '先看见问题',
    introModuleSim: '参与变化',
    introModuleSimTitle: '再模拟修复',
    introModuleData: '数据图表',
    introModuleDataTitle: '最后比较证据',
    homeTabsTitle: '学习模块',
    homeTabsDescription: '通过下方标签切换不同主题页面。',
    tabIntro: '概览',
    tabEmpathy: '影像',
    tabGame: '清理游戏',
    tabCleanup: '参与变化',
    tabChart: '数据',
    tabMap: '地图',
    tabImpact: '影响',
    tabActions: '行动',
    gameKicker: '清理游戏',
    gameTitle: '海洋垃圾清理游戏',
    gameDescription: '从海龟问诊开始，被污染的对象会一直显示；只有清空海面上的全部垃圾，它才会恢复原来的健康模样，再随机进入尚未体验的海域。',
    gameHeroLabel: '互动任务',
    gameHeroValue: '观察 · 清理 · 探索',
    gameHeroNote: '先观察被污染的对象，清除全部垃圾后，再见证它恢复原来的健康状态。',
    gameInstructions: '清理海面上的全部垃圾，先帮助第一位海龟恢复健康。',
    recycleBoat: '资源回收船',
    trashBoat: '一般垃圾船',
    debrisPlastic: '塑料瓶',
    debrisFishing: '渔具碎片',
    debrisOrganic: '夹杂海藻的垃圾',
    debrisOther: '发泡胶碎片',
    chartTitle: '日本周边海洋垃圾量：按垃圾类型看影响',
    chartDescription: '这里使用日本环境省的年度推计资料，把塑料垃圾、道路粉尘、衣物纤维、洗涤用品等可量化来源放在一起比较，让用户更直观地看到哪些日常垃圾正在影响日本周边海洋。',
    chartKicker: '数据证据',
    chartMethodLabel: '阅读方式',
    chartMethodValue: '日本周边 · 每年约多少吨',
    chartMethodNote: '把复杂的推计值换成更容易读懂的生活化数量。',
    chartInputLabel: '年度总量',
    chartInputValue: '每年约 1.6万-3.1万吨',
    chartInputNote: '日本环境省按来源和品目估算进入海洋的塑料垃圾总量。',
    chartPlasticLabel: '大块塑料垃圾',
    chartPlasticValue: '每年约 1,300-8,600 吨',
    chartPlasticNote: '包含被丢弃的塑料、海岸投弃物等看得见、捡得起的垃圾。',
    chartLandLabel: '微塑料粉尘',
    chartLandValue: '每年约 1.4万-2.0万吨',
    chartLandNote: '轮胎、道路标线、涂料、人工草坪等磨损后，会变成细小颗粒随雨水进入水域。',
    chartRiverLabel: '衣物纤维与洗剂',
    chartRiverValue: '纤维约 230-240 吨',
    chartRiverNote: '洗衣掉落的纤维、洗涤用品里的微胶囊，也会通过污水系统进入海洋。',
    chartCompositionLabel: '类型对比',
    chartCompositionTitle: '哪些垃圾正在流向日本周边海洋',
    chartHighlightOne: '最大项来自轮胎、道路标线等磨损粉尘',
    chartHighlightTwo: '衣物纤维来自每一次日常洗衣',
    chartHighlightThree: '洗剂香味胶囊虽少，却很贴近日常生活',
    chartVolumeTotalLabel: '日本海洋塑料垃圾流出总量',
    chartVolumeNote: '包含大块塑料、微塑料、洗衣纤维、洗剂香味胶囊、道路和轮胎粉尘等已可估算项目。',
    chartDetailsKicker: '来源说明',
    chartDetailsTitle: '数据从哪里来，应该怎么读',
    chartLegendRecycle: '拦截与治理界面',
    chartLegendTrash: '垃圾量较高界面',
    chartSourceMOEEstimate: '环境省量化资料',
    chartSourceMOE2025: '环境省 FY2025',
    chartSourceMOE2025Short: '环境省 FY2025',
    chartSourceMOESurvey: '海洋ごみ実態把握調査',
    chartSourceNote: '口径提醒',
    chartSourceMOEEstimateTitle: '海洋垃圾量化方法',
    chartSourceMOEEstimateText: '用于说明环境省如何按来源和品目估算进入海洋的垃圾量。',
    chartSourceMOE2025Title: '令和7年度検討結果',
    chartSourceMOE2025Text: '用于塑料垃圾总量、微塑料、纤维、洗剂等类别的年度区间。',
    chartSourceMOESurveyTitle: '调查报告索引',
    chartSourceMOESurveyText: '用于追溯日本海洋垃圾调查、漂着垃圾、漂流垃圾和海底垃圾相关年度报告。',
    chartSourceNoteTitle: '这些数值是暂定估算',
    chartSourceNoteText: '页面用来帮助理解数量级和类型差异，不代表海里每一件垃圾都已被精确数完。',
    mapKicker: '沿海影响',
    mapTitle: '把日本沿岸垃圾影响放到地图上看',
    mapDescription: '把环境省和研究资料中的可靠量级，放到日本沿海的代表性位置上看：哪里更像“入口”，哪里更像“堆积区”，哪里会先影响渔业、珊瑚和海鸟。',
    mapHeroLabel: '地图阅读',
    mapHeroValue: '点位 · 量级 · 影响',
    mapHeroNote: '点击地图点，查看对应沿海环境的垃圾来源、数量级和生态影响。',
    mapReadLabel: '读图方式',
    mapReadTitle: '点越大，代表这个位置对应的垃圾影响越需要关注',
    mapReadText: '点位不是精确到每个港湾的总量统计，而是把官方总量、回收量和调查证据转译成更容易理解的沿海影响地图。',
    mapLow: '低',
    mapMedium: '中',
    mapHigh: '高',
    mapWeightLow: '低影响',
    mapWeightMedium: '中等影响',
    mapWeightHigh: '高影响',
    mapFilterAll: '全部',
    mapNoData: '没有符合该筛选条件的区域数据。',
    mapAmountLabel: '垃圾量级',
    mapImpactLabel: '主要影响',
    mapSourceOne: '环境省 FY2025',
    mapSourceOneTitle: '日本海洋塑料垃圾流出量推计',
    mapSourceTwo: '环境省调查索引',
    mapSourceTwoTitle: '海洋ごみ実態把握調査',
    impactTitle: '海洋垃圾不是漂在远处的问题',
    impactDescription: '它会从海面、海底、食物链和沿岸社区同时进入生态系统。理解影响路径，才能判断清理和减量该从哪里开始。',
    impactKicker: '生态影响',
    impactSignalLabel: '风险信号',
    impactSignalValue: '缠绕 · 摄入 · 微塑料',
    impactSignalNote: '从单件垃圾扩散为长期生态压力',
    impactExploreButton: '查看影响路径',
    impactChainKicker: '影响路径',
    impactChainTitle: '一件垃圾，如何扩散成系统性压力',
    impactChainDescription: '选择一条路径，观察海洋垃圾如何从一次接触继续传递到生物、栖息地与食物链。',
    impactPathOneTitle: '误食与营养损失',
    impactPathOneText: '透明塑料、瓶盖和泡沫碎片容易被鱼类、海鸟和海龟误认为食物，造成饱腹假象和消化阻塞。',
    impactPathOneFlow: '误认食物 → 摄入 → 营养不足',
    impactPathTwoTitle: '渔具缠绕与幽灵捕捞',
    impactPathTwoText: '废弃渔网和绳索会持续缠住鱼类、海鸟和哺乳动物，也会破坏海草床与礁体结构。',
    impactPathTwoFlow: '持续漂流 → 缠绕 → 幽灵捕捞',
    impactPathThreeTitle: '微塑料进入食物链',
    impactPathThreeText: '碎裂后的微塑料更难回收，会被浮游生物和小型鱼类摄入，并沿食物链向上移动。',
    impactPathThreeFlow: '不断碎裂 → 小型生物摄入 → 进入食物链',
    impactDetailLabel: '当前影响链',
    impactDetailFlowLabel: '扩散过程',
    impactSystemKicker: '影响范围',
    impactSystemTitle: '影响不会停在海岸线',
    impactSystemDescription: '同一件垃圾可能漂浮、沉降、碎裂，最终影响沿岸环境和社区生活。',
    impactInsightOneValue: '海面',
    impactInsightOneText: '漂浮垃圾聚集在港湾、河口和洋流交汇处，影响景观、航行和近岸生物。',
    impactInsightTwoValue: '海底',
    impactInsightTwoText: '沉降垃圾会覆盖底栖生物栖息地，改变原本稳定的泥沙和礁石环境。',
    impactInsightThreeValue: '社区',
    impactInsightThreeText: '清理成本、渔获品质和旅游体验都会受到影响，环境问题最终回到人的生活。',
    impactLensKicker: '视觉对照',
    impactLensTitle: '同一片海域，两种未来',
    impactLensDescription: '切换视角，对比垃圾持续累积与生态恢复之后的环境差异。',
    impactLensCurrent: '当前压力',
    impactLensRestored: '恢复之后',
    impactLensCurrentCaption: '垃圾在海面与水下同时累积，生态压力不会停留在肉眼可见的位置。',
    impactLensRestoredCaption: '减少流入并持续清理后，水下栖息地和生物活动能够逐步恢复。',
    impactLensCurrentAlt: '受到垃圾压力的日本沿岸海域',
    impactLensRestoredAlt: '恢复清澈与生机的日本沿岸海域',
    impactNextKicker: '下一步',
    impactNextTitle: '看见影响之后，把理解变成行动',
    impactNextDescription: '从减少一次性用品、正确分类，到参加沿岸清理，每个动作都在减少下一次进入海洋的垃圾。',
    impactNextButton: '查看行动计划',
    impactNorthTitle: '北日本',
    impactNorthText: '塑料碎片随流冰漂流，对海鸟和海象构成威胁。',
    impactWestTitle: '西日本',
    impactWestText: '九州和濑户内海的渔具与塑料袋影响渔业资源。',
    impactSouthTitle: '西南诸岛',
    impactSouthText: '珊瑚礁周边的塑料碎片和微塑料增加生态系统压力。',
    actionsKicker: '行动计划',
    actionsTitle: '把海洋保护变成每天能完成的小动作',
    actionsDescription: '真正有效的行动不是一次性的热情，而是减少源头、正确回收、参与社区、持续记录四件事一起发生。',
    actionsImpactLabel: '优先级',
    actionsImpactValue: '少产生 · 不流入 · 可追踪',
    actionsImpactNote: '从源头减量比事后清理更有效',
    actionOneTitle: '减少一次性塑料',
    actionOne: '自带水杯、购物袋和餐具，把最容易进入河道的轻质包装先减下来。',
    actionTwoTitle: '把垃圾留在系统内',
    actionTwo: '饮料瓶、罐、玻璃和泡沫要清空、压缩、分类，让它们进入回收链而不是海岸线。',
    actionThreeTitle: '参加清理并记录',
    actionThree: '参与海岸或河道清理，记录常见垃圾类型，帮助判断真正需要治理的源头。',
    actionFourTitle: '影响身边选择',
    actionFour: '在学校、社团或店铺推动补水点、分类提示和可重复使用方案，让行动变成默认选项。',
    actionsCommunityKicker: '团队协作',
    actionsCommunityTitle: '从个人习惯扩大到社区机制',
    actionsCommunityText: '如果你能组织一次活动，重点不是“捡了多少”，而是把垃圾类型、地点、天气和参与人数记录下来。下一次行动就能更精准。',
    footerText: 'copyright © 2026 KCGI group 22 All rights reserved.',
    chartCanvasTitle: '日本周边海洋垃圾量',
    regionValueSuffix: '的沿海影响指数。',
    instructionCorrect: '✅ {item} — 得分 +{score}。当前总分: {totalScore}。',
    instructionWrong: '❌ {item} 放错了，请再试一次。',
    instructionUnknown: '未知垃圾。请放回正确位置。',
    empathyKicker: '影像观察',
    empathyTitle: '用真实影像看见日本沿岸海洋垃圾',
    empathyDescription: '通过视频和日本沿岸图片，把抽象的海洋垃圾问题变成可以看见、可以感受、可以讨论的现实场景。',
    empathyHeroLabel: '观看重点',
    empathyHeroValue: '路径 · 生物 · 海岸',
    empathyHeroNote: '先看垃圾如何进入海洋，再看它与沿岸风景、生态和人类活动的关系。',
    videoKicker: '主题视频',
    videoTitle: '塑料如何进入海洋生态链',
    videoDescription: '通过短视频理解塑料垃圾从日常生活进入河流、海湾和海洋生物体内的路径。',
    imageCaption1: '北海道的渔村与漂流垃圾',
    imageCaption2: '冲绳珊瑚礁与海洋生物',
    imageCaption3: '渔业与海洋环境的联系',
    officialImageNote: '图片来源：日本环境省（公開資料）',
    impactInteractiveTitle: '亲手参与，观察变化',
    impactInteractiveDescription: '每次清理动作都会改变水质和生机，体验“手动修复”的过程。',
    cleanupKicker: '参与变化',
    cleanupHeroLabel: '模拟体验',
    cleanupHeroValue: '当前 · 部分 · 完全',
    cleanupHeroNote: '切换清理程度，观察水质、垃圾量和海洋生物状态如何变化。',
    beforeLabel: '清理前',
    afterLabel: '清理后',
    cleanupFieldKicker: '现场观察记录',
    cleanupFieldTitle: '清理不只改变照片，也留下可以核对的数据',
    cleanupFieldPeople: '名志愿者参加',
    cleanupFieldWeight: '漂着垃圾被回收',
    cleanupFieldSteps: '个阶段持续观察',
    cleanupFieldText: '观察重点包括岸线上的垃圾密度、清理中的分类回收，以及清理后是否仍有细碎塑料和渔网残留。',
    cleanupFieldSource: '资料：冲绳县 2024 年照间海岸清理成果',
    cleanupEvidenceKicker: '日本实景档案',
    cleanupEvidenceTitle: '从发现污染，到清理，再到恢复后的海岸',
    cleanupEvidenceNote: '以下为日本环境省与冲绳县公开的真实现场照片；三张照片用于说明不同清理阶段，并非同一地点的连续对照。',
    impactPhoto1: '清理前：垃圾已经缠上海滨植物',
    impactPhoto2: '部分清理：志愿者正在分类和回收',
    impactPhoto3: '完全清理：岸线恢复整洁',
    impactPhotoSourceOne: '出处：环境省关东地方环境事务所',
    impactPhotoSourceTwo: '出处：冲绳县照间海岸清理成果',
    impactPhotoSourceThree: '出处：冲绳县公开的清理后照片',
    cleanupImageNote: '图片著作权归原发布机构所有，点击每张照片下方的出处可查看原始页面。',
    gameDashboardKicker: '海洋问诊单',
    gameDashboardTitle: '清理进度面板',
    gamePatientNameLabel: '对象',
    gamePatientName: '海龟',
    gamePatientHabitatLabel: '来源海域',
    gamePatientHabitat: '日本周边海域',
    gamePollutionLabel: '主要污染',
    gameTreatmentLabel: '治疗内容',
    gameDebrisCountLabel: '海面垃圾',
    gameHealthLabel: '环境健康度',
    gameScoreLabel: '得分',
    gameCorrectLabel: '正确投放',
    gameRemainingLabel: '剩余垃圾',
    gameAccuracyLabel: '正确率',
    gameProgressText: '已完成 {cleaned} / {total} 个关卡',
    gameRoundText: '第 {current} 站 / 共 {total} 站',
    gameRemainingLevelsText: '还有 {remaining} 个海域等待问诊',
    gameAllStationsComplete: '所有海域问诊完成',
    gameDebrisCountText: '已清理 {cleaned} / {total} 件',
    gameLevelInstruction: '正在问诊来自{sea}的{animal}，主要污染是“{pollution}”。请清理海面上的全部 {total} 件垃圾。',
    gameLevelProgressMessage: '已清理 {cleaned} / {total} 件垃圾。继续清空海面，完成“{treatment}”。',
    gameLevelCompleteMessage: '{animal}的治疗已经完成。下一站将从尚未体验的海域中随机选出。',
    gameAllCompleteMessage: '5 个海域全部问诊完成，所有生物和环境都恢复了健康。',
    gameCleanedMessage: '已经清理一件垃圾，海水变得更清透，海龟的健康度也在回升。',
    gameCompleteMessage: '治疗成功！海面垃圾已经全部清理，海龟健康度恢复到 100%。',
    gameAnimalAlt: '受海洋垃圾影响的{animal}',
    gamePollutedAnimalAlt: '被海洋垃圾污染的{animal}',
    gameRestoredAnimalAlt: '清理后恢复健康的{animal}',
    gameDebrisAlt: '漂浮在海面上的{debris}',
    gameDebrisButtonLabel: '清理{debris}',
    gameTurtleAlt: '受海洋垃圾影响的海龟',
    gameTrashPlasticAlt: '漂浮的塑料垃圾',
    gameTrashBottleAlt: '海面上的塑料瓶',
    gameTrashNetAlt: '废弃渔网',
    randomNextLevelButton: '随机前往下一海域',
    nextLevelLockedButton: '清空后随机前往下一关',
    restartSessionButton: '从海龟关重新开始',
    restartGameButton: '重新清理本关',
    gameStep1: '{animal}来自{sea}。',
    gameStep2: '本关共有 {total} 件垃圾，其中主要污染是“{pollution}”。',
    gameStep3: '清空海面后，随机进入一个尚未体验的海域。',
    statusText: '水质恢复: {percent}%',
    simulationTitle: '模拟影响',
    simulationCurrent: '当前状态',
    simulationPartial: '部分清理',
    simulationFull: '完全清理',
    simulationImageAltCurrent: '污染的海洋与漂浮垃圾',
    simulationImageAltPartial: '部分清理后的海岸，仍可见垃圾',
    simulationImageAltFull: '清澈海水与健康海洋生物',
    simulationImageCaptionCurrent: '漂浮垃圾污染水体',
    simulationImageCaptionPartial: '部分清理后仍需继续努力',
    simulationImageCaptionFull: '彻底清理后的健康海洋',
    debrisLevelLabel: '垃圾量',
    marineLifeLabel: '海洋生物',
    waterColorLabel: '海水',
    marineLifePoor: '受损',
    marineLifeModerate: '恢复中',
    marineLifeHealthy: '健康',
    waterCloudy: '浑浊',
    waterModerate: '逐渐清澈',
    waterClear: '清澈'
  },
  en: {
    heroEyebrow: 'Protect Japan’s coastal seas',
    languageLabel: 'Language',
    heroTitle: 'Marine debris impacts on Japan’s ocean environment',
    heroSubtitle: 'Experience how floating plastics, fishing gear, and bottles burden marine life around Japan’s coasts.',
    startButton: 'Start Experience',
    introTitle: 'Understand marine debris near Japan through interaction',
    introText: 'Real imagery, cleanup simulation, charts, and maps turn the question of ocean debris into a path you can observe, click, and compare.',
    introKicker: 'Learning entry',
    introMetricOneLabel: 'Main source',
    introMetricOneText: 'Estimated share from land-based inputs',
    introMetricTwoLabel: 'Key types',
    introMetricTwoText: 'Bottles, fishing gear, foam, cans, and glass',
    introMetricThreeLabel: 'Learning modes',
    introMetricThreeText: 'Imagery, game, simulation, data, maps, and action',
    introModuleVisual: 'Visuals',
    introModuleVisualTitle: 'See the issue first',
    introModuleSim: 'Hands-on',
    introModuleSimTitle: 'Simulate recovery',
    introModuleData: 'Data',
    introModuleDataTitle: 'Compare evidence',
    homeTabsTitle: 'Learning Modules',
    homeTabsDescription: 'Switch topic pages quickly with the tabs below.',
    tabIntro: 'Overview',
    tabEmpathy: 'Imagery',
    tabGame: 'Cleanup Game',
    tabCleanup: 'Hands-on',
    tabChart: 'Data',
    tabMap: 'Map',
    tabImpact: 'Impact',
    tabActions: 'Actions',
    gameKicker: 'Cleanup game',
    gameTitle: 'Marine debris cleanup game',
    gameDescription: 'Begin with the sea turtle. The polluted subject remains visible until every debris item is cleared, then returns to its original healthy form before the next random unvisited sea.',
    gameHeroLabel: 'Interactive task',
    gameHeroValue: 'Observe · Clean · Explore',
    gameHeroNote: 'Observe the polluted subject, remove every debris item, and reveal its original healthy state.',
    gameInstructions: 'Clear every item from the water to help the first sea turtle recover.',
    recycleBoat: 'Recycle Boat',
    trashBoat: 'Trash Boat',
    debrisPlastic: 'Plastic bottle',
    debrisFishing: 'Fishing gear fragment',
    debrisOrganic: 'Seaweed mixed debris',
    debrisOther: 'Styrofoam piece',
    chartTitle: 'Marine debris volume around Japan by waste type',
    chartDescription: 'This page uses annual estimates from Japan’s Ministry of the Environment to compare quantifiable sources such as plastic litter, road dust, textile fibers, and detergent-related microplastics.',
    chartKicker: 'Data evidence',
    chartMethodLabel: 'How to read',
    chartMethodValue: 'Japan waters · tons each year',
    chartMethodNote: 'Complex estimates are rewritten as more readable everyday quantities.',
    chartInputLabel: 'Annual total',
    chartInputValue: 'About 16,000-31,000 tons each year',
    chartInputNote: 'MOE estimates Japan’s marine plastic litter outflow by source and item.',
    chartPlasticLabel: 'Large plastic litter',
    chartPlasticValue: 'About 1,300-8,600 tons each year',
    chartPlasticNote: 'Visible plastic litter such as discarded plastic and coastal litter.',
    chartLandLabel: 'Microplastic dust',
    chartLandValue: 'About 14,000-20,000 tons each year',
    chartLandNote: 'Tires, road markings, paint, and artificial turf wear down into small particles that can wash into waterways.',
    chartRiverLabel: 'Textile fibers and detergents',
    chartRiverValue: 'Textile fibers: about 230-240 tons',
    chartRiverNote: 'Laundry fibers and fragrance capsules in detergents can move toward the sea through wastewater systems.',
    chartCompositionLabel: 'Type comparison',
    chartCompositionTitle: 'Which waste types flow toward Japanese waters',
    chartHighlightOne: 'The largest category comes from tire and road-marking wear',
    chartHighlightTwo: 'Textile fibers start with everyday laundry',
    chartHighlightThree: 'Detergent fragrance capsules are small but close to daily life',
    chartVolumeTotalLabel: 'Japan marine plastic litter outflow total',
    chartVolumeNote: 'Includes estimable items such as large plastic litter, microplastics, textile fibers, detergent fragrance capsules, and road or tire dust.',
    chartDetailsKicker: 'Source notes',
    chartDetailsTitle: 'Where the data comes from and how to read it',
    chartLegendRecycle: 'Interception interface',
    chartLegendTrash: 'Higher-volume interface',
    chartSourceMOEEstimate: 'MOE quantified material',
    chartSourceMOE2025: 'MOE FY2025',
    chartSourceMOE2025Short: 'MOE FY2025',
    chartSourceMOESurvey: 'Marine litter survey',
    chartSourceNote: 'Scope note',
    chartSourceMOEEstimateTitle: 'Quantifying marine litter',
    chartSourceMOEEstimateText: 'Used to explain how MOE estimates marine outflow by source and item.',
    chartSourceMOE2025Title: 'FY2025 study results',
    chartSourceMOE2025Text: 'Used for annual ranges for plastic litter, microplastics, fibers, and detergent-related items.',
    chartSourceMOESurveyTitle: 'Survey report index',
    chartSourceMOESurveyText: 'Used to trace annual reports on Japanese marine litter, washed-ashore litter, floating litter, and seabed litter.',
    chartSourceNoteTitle: 'These figures are provisional estimates',
    chartSourceNoteText: 'They help compare scale and type, but they do not mean every item in the sea has been counted precisely.',
    mapKicker: 'Coastal impact',
    mapTitle: 'See Japan’s coastal debris impact on the map',
    mapDescription: 'Reliable estimates from MOE and research sources are placed onto representative coastal points so users can see likely entry areas, accumulation zones, and impacts on fisheries, coral, and seabirds.',
    mapHeroLabel: 'Map reading',
    mapHeroValue: 'Points · Scale · Impact',
    mapHeroNote: 'Click a map point to see the debris source, quantity cue, and ecological impact for that coastal setting.',
    mapReadLabel: 'How to read',
    mapReadTitle: 'Larger points mark coastal impacts that need more attention',
    mapReadText: 'Points are not precise port-by-port totals. They translate official totals, recovery data, and survey evidence into an easy-to-read coastal impact map.',
    mapLow: 'Low',
    mapMedium: 'Medium',
    mapHigh: 'High',
    mapWeightLow: 'Lower impact',
    mapWeightMedium: 'Medium impact',
    mapWeightHigh: 'High impact',
    mapFilterAll: 'All',
    mapNoData: 'No region data matches this filter.',
    mapAmountLabel: 'Quantity cue',
    mapImpactLabel: 'Main impact',
    mapSourceOne: 'MOE FY2025',
    mapSourceOneTitle: 'Estimate of Japan’s marine plastic litter outflow',
    mapSourceTwo: 'MOE survey index',
    mapSourceTwoTitle: 'Marine litter survey reports',
    impactTitle: 'Marine debris is not a distant problem',
    impactDescription: 'It enters the surface, seabed, food web, and coastal communities at the same time. Following the pathway helps decide where cleanup and reduction should begin.',
    impactKicker: 'Ecological impact',
    impactSignalLabel: 'Risk signals',
    impactSignalValue: 'Entanglement · ingestion · microplastics',
    impactSignalNote: 'A single item can become long-term ecological pressure',
    impactExploreButton: 'Explore the pathways',
    impactChainKicker: 'Impact pathways',
    impactChainTitle: 'How one item becomes system-wide pressure',
    impactChainDescription: 'Choose a pathway to see how marine debris moves from one encounter into wildlife, habitats, and the food web.',
    impactPathOneTitle: 'Ingestion and nutrition loss',
    impactPathOneText: 'Clear plastic, caps, and foam fragments can be mistaken for food by fish, seabirds, and turtles, causing false fullness and blockage.',
    impactPathOneFlow: 'Mistaken for food → ingestion → nutrition loss',
    impactPathTwoTitle: 'Fishing gear entanglement',
    impactPathTwoText: 'Discarded nets and ropes keep trapping animals and can damage seagrass beds and reef structures.',
    impactPathTwoFlow: 'Drifting → entanglement → ghost fishing',
    impactPathThreeTitle: 'Microplastics in the food web',
    impactPathThreeText: 'Fragmented plastic is harder to recover and can move upward after plankton and small fish ingest it.',
    impactPathThreeFlow: 'Fragmentation → small organisms ingest → food web',
    impactDetailLabel: 'Current impact chain',
    impactDetailFlowLabel: 'How it spreads',
    impactSystemKicker: 'Reach of impact',
    impactSystemTitle: 'The impact does not stop at the shoreline',
    impactSystemDescription: 'The same item can drift, sink, and fragment before affecting coastal habitats and community life.',
    impactInsightOneValue: 'Surface',
    impactInsightOneText: 'Floating debris collects near ports, river mouths, and current boundaries, affecting scenery, navigation, and coastal life.',
    impactInsightTwoValue: 'Seabed',
    impactInsightTwoText: 'Sinking debris covers habitats for bottom-dwelling species and changes sediment and reef conditions.',
    impactInsightThreeValue: 'Community',
    impactInsightThreeText: 'Cleanup cost, seafood quality, and tourism are affected, bringing the environmental issue back into daily life.',
    impactLensKicker: 'Visual comparison',
    impactLensTitle: 'One sea, two possible futures',
    impactLensDescription: 'Switch views to compare continued debris accumulation with an ecosystem after recovery.',
    impactLensCurrent: 'Current pressure',
    impactLensRestored: 'After recovery',
    impactLensCurrentCaption: 'Debris accumulates above and below the surface, spreading pressure beyond what is immediately visible.',
    impactLensRestoredCaption: 'Reducing inflow and sustaining cleanup allows underwater habitats and marine activity to recover.',
    impactLensCurrentAlt: 'Japanese coastal water under pressure from marine debris',
    impactLensRestoredAlt: 'Clear and recovering Japanese coastal water',
    impactNextKicker: 'Next step',
    impactNextTitle: 'Turn understanding into action',
    impactNextDescription: 'Reducing disposables, sorting correctly, and joining coastal cleanup each prevents the next item from reaching the sea.',
    impactNextButton: 'View the action plan',
    impactNorthTitle: 'Northern Japan',
    impactNorthText: 'Plastic fragments drift with sea ice, threatening seabirds and seals.',
    impactWestTitle: 'Western Japan',
    impactWestText: 'Fishing gear and plastic sheets affect fisheries in Kyushu and the Seto Inland Sea.',
    impactSouthTitle: 'Southwest Islands',
    impactSouthText: 'Plastic fragments and microplastics stress coral reef ecosystems.',
    actionsKicker: 'Action plan',
    actionsTitle: 'Turn ocean protection into small daily actions',
    actionsDescription: 'Effective action is not a one-time burst of enthusiasm. It combines source reduction, correct recovery, community participation, and continuous tracking.',
    actionsImpactLabel: 'Priority',
    actionsImpactValue: 'Reduce · contain · track',
    actionsImpactNote: 'Reducing at the source is more effective than cleaning afterward.',
    actionOneTitle: 'Reduce single-use plastic',
    actionOne: 'Carry a bottle, bag, and utensils to cut lightweight packaging that can easily enter waterways.',
    actionTwoTitle: 'Keep waste inside the system',
    actionTwo: 'Empty, compress, and sort bottles, cans, glass, and foam so they return to recovery streams instead of coastlines.',
    actionThreeTitle: 'Join cleanups and record data',
    actionThree: 'Take part in coastal or river cleanup and record common debris types to reveal the source that needs attention.',
    actionFourTitle: 'Influence nearby choices',
    actionFour: 'Promote refill points, sorting prompts, and reusable options in schools, groups, or local shops.',
    actionsCommunityKicker: 'Team practice',
    actionsCommunityTitle: 'Scale personal habits into community systems',
    actionsCommunityText: 'If you organize an activity, the goal is not only how much you collect. Record debris types, location, weather, and participants so the next action becomes sharper.',
    footerText: 'copyright © 2026 KCGI group 22 All rights reserved.',
    chartCanvasTitle: 'Marine debris volume around Japan',
    regionValueSuffix: ' coastal impact score.',
    instructionCorrect: '✅ {item} — +{score} points. Total: {totalScore}.',
    instructionWrong: '❌ {item} is not correct. Try again.',
    instructionUnknown: 'Unknown debris. Put it back in the correct place.',
    empathyKicker: 'Visual observation',
    empathyTitle: 'See marine debris along Japan’s coast through real imagery',
    empathyDescription: 'Video and coastal imagery turn the abstract issue of marine debris into scenes users can see, feel, and discuss.',
    empathyHeroLabel: 'Viewing focus',
    empathyHeroValue: 'Pathways · Life · Coasts',
    empathyHeroNote: 'Start with how debris enters the sea, then connect it to coastal scenery, ecosystems, and human activity.',
    videoKicker: 'Featured video',
    videoTitle: 'How plastic enters the marine food web',
    videoDescription: 'A short video explains how everyday plastic waste moves from daily life into rivers, bays, and marine animals.',
    imageCaption1: 'Fishing village with coastal debris',
    imageCaption2: 'Coral life near Okinawa',
    imageCaption3: 'Fishing communities and ocean health',
    officialImageNote: 'Image source: Ministry of the Environment, Japan (public pages).',
    impactInteractiveTitle: 'Participate and observe change',
    impactInteractiveDescription: 'Each cleanup action changes water quality and marine life, showing restoration in real time.',
    cleanupKicker: 'Participate and change',
    cleanupHeroLabel: 'Simulation',
    cleanupHeroValue: 'Current · Partial · Full',
    cleanupHeroNote: 'Switch cleanup levels and observe changes in water quality, debris amount, and marine life.',
    beforeLabel: 'Before cleanup',
    afterLabel: 'After cleanup',
    cleanupFieldKicker: 'Field observation notes',
    cleanupFieldTitle: 'Cleanup changes more than the photo; it creates evidence we can check',
    cleanupFieldPeople: 'volunteers joined',
    cleanupFieldWeight: 'of stranded debris recovered',
    cleanupFieldSteps: 'stages observed',
    cleanupFieldText: 'Observe shoreline debris density, sorting during cleanup, and whether fragments or fishing nets remain afterward.',
    cleanupFieldSource: 'Source: Okinawa Prefecture, 2024 Teruma coast cleanup results',
    cleanupEvidenceKicker: 'Real scenes from Japan',
    cleanupEvidenceTitle: 'From finding pollution, through cleanup, to a restored coast',
    cleanupEvidenceNote: 'These are real field photographs published by Japan’s Ministry of the Environment and Okinawa Prefecture. They illustrate cleanup stages and are not a continuous comparison of one site.',
    impactPhoto1: 'Before cleanup: debris entangled in coastal plants',
    impactPhoto2: 'Partial cleanup: volunteers sorting and collecting',
    impactPhoto3: 'Full cleanup: a clear shoreline after recovery',
    impactPhotoSourceOne: 'Source: Kanto Regional Environment Office',
    impactPhotoSourceTwo: 'Source: Okinawa Prefecture Teruma cleanup results',
    impactPhotoSourceThree: 'Source: post-cleanup photo published by Okinawa Prefecture',
    cleanupImageNote: 'Image rights belong to the publishing organizations. Use the source link below each photograph to view the original page.',
    gameDashboardKicker: 'Ocean diagnosis',
    gameDashboardTitle: 'Cleanup progress panel',
    gamePatientNameLabel: 'Subject',
    gamePatientName: 'Sea turtle',
    gamePatientHabitatLabel: 'Source sea',
    gamePatientHabitat: 'Waters around Japan',
    gamePollutionLabel: 'Main pollution',
    gameTreatmentLabel: 'Treatment',
    gameDebrisCountLabel: 'Surface debris',
    gameHealthLabel: 'Environmental health',
    gameScoreLabel: 'Score',
    gameCorrectLabel: 'Correct drops',
    gameRemainingLabel: 'Remaining',
    gameAccuracyLabel: 'Accuracy',
    gameProgressText: 'Levels complete: {cleaned} / {total}',
    gameRoundText: 'Stop {current} of {total}',
    gameRemainingLevelsText: '{remaining} seas awaiting diagnosis',
    gameAllStationsComplete: 'All diagnoses complete',
    gameDebrisCountText: '{cleaned} of {total} cleared',
    gameLevelInstruction: 'Diagnose the {animal} from {sea}. The main pollution is “{pollution}”. Clear all {total} debris items from the water.',
    gameLevelProgressMessage: '{cleaned} of {total} items cleared. Remove the rest to complete “{treatment}”.',
    gameLevelCompleteMessage: 'The {animal} treatment is complete. The next stop will be selected at random from unvisited seas.',
    gameAllCompleteMessage: 'All five seas have been diagnosed, and every animal and habitat has recovered.',
    gameCleanedMessage: 'One debris item has been removed. The water is clearing and the turtle’s health is rising.',
    gameCompleteMessage: 'Treatment successful. All debris is cleared and the turtle’s health has returned to 100%.',
    gameAnimalAlt: '{animal} affected by marine debris',
    gamePollutedAnimalAlt: '{animal} polluted by marine debris',
    gameRestoredAnimalAlt: '{animal} restored after cleanup',
    gameDebrisAlt: '{debris} floating in the water',
    gameDebrisButtonLabel: 'Remove {debris}',
    gameTurtleAlt: 'Sea turtle affected by marine debris',
    gameTrashPlasticAlt: 'Floating plastic debris',
    gameTrashBottleAlt: 'Plastic bottle floating in the sea',
    gameTrashNetAlt: 'Discarded fishing net',
    randomNextLevelButton: 'Choose a random next sea',
    nextLevelLockedButton: 'Clear the sea to continue',
    restartSessionButton: 'Restart from the turtle',
    restartGameButton: 'Restart this cleanup',
    gameStep1: 'The {animal} comes from {sea}.',
    gameStep2: 'Clear {total} items, including the main pollutant “{pollution}”.',
    gameStep3: 'After cleanup, continue to a random sea you have not visited yet.',
    statusText: 'Water quality restored: {percent}%',
    simulationTitle: 'Impact simulation',
    simulationCurrent: 'Current state',
    simulationPartial: 'Partial cleanup',
    simulationFull: 'Full cleanup',
    simulationImageAltCurrent: 'Polluted ocean water with plastic debris',
    simulationImageAltPartial: 'Partially cleaned coast with remaining debris',
    simulationImageAltFull: 'Clear ocean water with healthy marine life',
    simulationImageCaptionCurrent: 'Polluted water with floating debris',
    simulationImageCaptionPartial: 'Partial cleanup still needs more care',
    simulationImageCaptionFull: 'Healthy ocean after full cleanup',
    debrisLevelLabel: 'Debris amount',
    marineLifeLabel: 'Marine life',
    waterColorLabel: 'Seawater',
    marineLifePoor: 'Stressed',
    marineLifeModerate: 'Recovering',
    marineLifeHealthy: 'Healthy',
    waterCloudy: 'Cloudy',
    waterModerate: 'Clearing',
    waterClear: 'Clear'
  }
};

/**
 * 游戏垃圾数据
 * Game debris data
 * 定义不同类型垃圾的属性：目标容器、标签键和分数
 * Defines properties for different debris types: target container, label key, and score
 */
const debrisPieces = {
  plastic: { target: 'recycle', labelKey: 'debrisPlastic', score: 10 },
  fishing: { target: 'trash', labelKey: 'debrisFishing', score: 8 },
  organic: { target: 'recycle', labelKey: 'debrisOrganic', score: 6 },
  other: { target: 'trash', labelKey: 'debrisOther', score: 5 }
};

/**
 * 图表数据
 * Chart data
 * 日本周边海洋垃圾类型年度量级指标
 * Annual item/source indicators for marine debris around Japan
 */
const chartData = [
  // 数值单位统一为“吨/年”；min/max 表示官方推计区间，不是现场逐件统计。
  { key: 'japanPlasticOutflowTotal', labelKey: 'chartJapanPlasticOutflowTotal', sourceKey: 'chartSourceMOE2025Short', min: 16000, max: 31000, type: 'total' },
  { key: 'japanMacroPlastic', labelKey: 'chartJapanMacroPlastic', sourceKey: 'chartSourceMOE2025Short', min: 1300, max: 8600, type: 'macro' },
  { key: 'japanUnintentionalMicroplastic', labelKey: 'chartJapanUnintentionalMicroplastic', sourceKey: 'chartSourceMOE2025Short', min: 14000, max: 20000, type: 'micro' },
  { key: 'japanIntentionalMicroplastic', labelKey: 'chartJapanIntentionalMicroplastic', sourceKey: 'chartSourceMOE2025Short', min: 610, max: 2500, type: 'additive' },
  { key: 'japanTextileFiber', labelKey: 'chartJapanTextileFiber', sourceKey: 'chartSourceMOE2025Short', min: 230, max: 240, type: 'fiber' },
  { key: 'japanResinPellet', labelKey: 'chartJapanResinPellet', sourceKey: 'chartSourceMOE2025Short', min: 100, max: 840, type: 'pellet' },
  { key: 'japanDetergentCapsules', labelKey: 'chartJapanDetergentCapsules', sourceKey: 'chartSourceMOE2025Short', min: 0.5, max: 5, type: 'detergent' }
];

/**
 * 地图点位数据
 * Map point data
 * 以可靠资料的全国量级和代表性沿海环境，解释日本沿岸垃圾影响
 * Explains debris impact along Japan's coast using reliable national-scale evidence and representative coastal settings
 */
const regionMapData = [
  // value 是 0-100 的展示指数，只控制点位大小和关注等级，不代表该地点的垃圾吨数。
  {
    id: 'tokyo_bay',
    lat: 35.55,
    lng: 139.88,
    value: 92,
    weight: 'high',
    labelKey: 'regionTokyoBay',
    typeKey: 'mapTypeUrbanBay',
    amountKey: 'regionTokyoBayAmount',
    impactKey: 'regionTokyoBayImpact',
    evidenceKey: 'regionTokyoBayEvidence',
    descriptionKey: 'regionTokyoBayDescription',
    sourceKey: 'mapSourceMOE2025',
    sourceUrl: 'https://www.env.go.jp/content/000401106.pdf'
  },
  {
    id: 'osaka_bay_seto',
    lat: 34.45,
    lng: 135.15,
    value: 84,
    weight: 'high',
    labelKey: 'regionOsakaBaySeto',
    typeKey: 'mapTypeSemiClosedSea',
    amountKey: 'regionOsakaBaySetoAmount',
    impactKey: 'regionOsakaBaySetoImpact',
    evidenceKey: 'regionOsakaBaySetoEvidence',
    descriptionKey: 'regionOsakaBaySetoDescription',
    sourceKey: 'mapSourceMOE2025',
    sourceUrl: 'https://www.env.go.jp/content/000401106.pdf'
  },
  {
    id: 'tsushima_japan_sea',
    lat: 34.25,
    lng: 129.3,
    value: 78,
    weight: 'high',
    labelKey: 'regionTsushimaJapanSea',
    typeKey: 'mapTypeDriftCoast',
    amountKey: 'regionTsushimaJapanSeaAmount',
    impactKey: 'regionTsushimaJapanSeaImpact',
    evidenceKey: 'regionTsushimaJapanSeaEvidence',
    descriptionKey: 'regionTsushimaJapanSeaDescription',
    sourceKey: 'mapSourceMOESurvey',
    sourceUrl: 'https://www.env.go.jp/water/post_80.html'
  },
  {
    id: 'okinawa_coral',
    lat: 26.5,
    lng: 127.95,
    value: 72,
    weight: 'medium',
    labelKey: 'regionOkinawaCoral',
    typeKey: 'mapTypeCoral',
    amountKey: 'regionOkinawaCoralAmount',
    impactKey: 'regionOkinawaCoralImpact',
    evidenceKey: 'regionOkinawaCoralEvidence',
    descriptionKey: 'regionOkinawaCoralDescription',
    sourceKey: 'mapSourceOkinawaStudy',
    sourceUrl: 'https://arxiv.org/abs/2008.08259'
  },
  {
    id: 'sanriku_fishing',
    lat: 39.25,
    lng: 142.15,
    value: 66,
    weight: 'medium',
    labelKey: 'regionSanrikuFishing',
    typeKey: 'mapTypeFishing',
    amountKey: 'regionSanrikuFishingAmount',
    impactKey: 'regionSanrikuFishingImpact',
    evidenceKey: 'regionSanrikuFishingEvidence',
    descriptionKey: 'regionSanrikuFishingDescription',
    sourceKey: 'mapSourceMOE2025',
    sourceUrl: 'https://www.env.go.jp/content/000401106.pdf'
  },
  {
    id: 'hokkaido_okhotsk',
    lat: 44.3,
    lng: 143.6,
    value: 58,
    weight: 'medium',
    labelKey: 'regionHokkaidoOkhotsk',
    typeKey: 'mapTypeColdCurrent',
    amountKey: 'regionHokkaidoOkhotskAmount',
    impactKey: 'regionHokkaidoOkhotskImpact',
    evidenceKey: 'regionHokkaidoOkhotskEvidence',
    descriptionKey: 'regionHokkaidoOkhotskDescription',
    sourceKey: 'mapSourceMOESurvey',
    sourceUrl: 'https://www.env.go.jp/water/post_80.html'
  },
  {
    id: 'kyushu_west',
    lat: 32.1,
    lng: 130.0,
    value: 62,
    weight: 'medium',
    labelKey: 'regionKyushuWest',
    typeKey: 'mapTypeCurrentGate',
    amountKey: 'regionKyushuWestAmount',
    impactKey: 'regionKyushuWestImpact',
    evidenceKey: 'regionKyushuWestEvidence',
    descriptionKey: 'regionKyushuWestDescription',
    sourceKey: 'mapSourceMOESurvey',
    sourceUrl: 'https://www.env.go.jp/water/post_80.html'
  }
];

/**
 * 动态数据专用标签。
 * translations 负责页面固定文案；这里负责 chartData 与 regionMapData 中通过 *Key 引用的名称。
 * 两张表分开可避免大段地区说明混入页面级翻译，同时仍由 getLocalizedLabel 统一读取。
 */
const localizedLabels = {
  ja: {
    chartJapanPlasticOutflowTotal: '海洋プラスチックごみ総量',
    chartJapanMacroPlastic: '大きなプラスチックごみ',
    chartJapanUnintentionalMicroplastic: '摩耗で生まれる微細ごみ',
    chartJapanIntentionalMicroplastic: '製品に使われる微細ごみ',
    chartJapanTextileFiber: '洗濯で出る衣類繊維',
    chartJapanResinPellet: '樹脂ペレット・発泡ビーズ',
    chartJapanDetergentCapsules: '洗剤類の香りカプセル',
    mapTypeUrbanBay: '都市湾',
    mapTypeSemiClosedSea: '閉鎖性海域',
    mapTypeDriftCoast: '漂着海岸',
    mapTypeCoral: 'サンゴ礁',
    mapTypeFishing: '漁業沿岸',
    mapTypeColdCurrent: '寒流沿岸',
    mapTypeCurrentGate: '潮流の入口',
    mapSourceMOE2025: '環境省 FY2025 推計資料',
    mapSourceMOESurvey: '環境省 海洋ごみ調査',
    mapSourceOkinawaStudy: '沖縄沿岸マイクロプラスチック研究',
    regionTokyoBay: '東京湾・関東沿岸',
    regionTokyoBayAmount: '関連量級：日本全体で毎年約1.6万-3.1万トンが海へ流出',
    regionTokyoBayImpact: '都市排水・道路粉じん・河川流入',
    regionTokyoBayDescription: '人口と道路が集中する湾岸では、雨の日に街の粉じんや細かなプラスチックが河川を通じて海へ入りやすくなります。',
    regionTokyoBayEvidence: '環境省の推計では、摩耗で生まれる微細ごみが年間約1.4万-2万トンと大きな割合を占めます。',
    regionOsakaBaySeto: '大阪湾・瀬戸内海',
    regionOsakaBaySetoAmount: '関連量級：大きなプラスチックごみは毎年約1,300-8,600トン',
    regionOsakaBaySetoImpact: '閉じた海での滞留・漁業影響',
    regionOsakaBaySetoDescription: '湾や内海は水の入れ替わりが遅く、袋、発泡材、食品包装などが岸や漁場に残りやすい環境です。',
    regionOsakaBaySetoEvidence: '公式推計は、大きなプラスチックと微細化したプラスチックを分けて年間量を示しています。',
    regionTsushimaJapanSea: '対馬海峡・日本海側',
    regionTsushimaJapanSeaAmount: '目安：漂着ごみの多い海岸として重点的に観察',
    regionTsushimaJapanSeaImpact: '潮流で運ばれる漂着ごみ',
    regionTsushimaJapanSeaDescription: '対馬海流に沿って、ペットボトル、漁具、発泡材などが海岸へ打ち上がりやすい場所です。',
    regionTsushimaJapanSeaEvidence: '環境省の海洋ごみ実態把握調査は、漂着・漂流・海底ごみを継続的に扱っています。',
    regionOkinawaCoral: '沖縄・サンゴ礁沿岸',
    regionOkinawaCoralAmount: '目安：調査地点すべてで微小プラスチックを確認',
    regionOkinawaCoralImpact: 'サンゴ礁と食物連鎖への微細ごみ',
    regionOkinawaCoralDescription: '透明な水の海でも、目に見えにくい微小プラスチックは生きものの表面や餌の流れに入り込む可能性があります。',
    regionOkinawaCoralEvidence: '沖縄沿岸の研究では、全調査地点でプラスチック粒子が確認され、人の活動が多い場所ほど濃度が高い傾向でした。',
    regionSanrikuFishing: '三陸沿岸',
    regionSanrikuFishingAmount: '関連量級：海域回収分は全国推計で毎年約412トン',
    regionSanrikuFishingImpact: '漁具・ロープによる絡まり',
    regionSanrikuFishingDescription: '複雑なリアス海岸と漁場では、網やロープ片が残ると魚、海鳥、海獣の絡まりにつながります。',
    regionSanrikuFishingEvidence: '環境省資料では、海岸・海域・河川など複数の回収面から海洋ごみを整理しています。',
    regionHokkaidoOkhotsk: '北海道・オホーツク沿岸',
    regionHokkaidoOkhotskAmount: '目安：流氷・海流で運ばれる漂着ごみに注意',
    regionHokkaidoOkhotskImpact: '海鳥・海獣への誤食と絡まり',
    regionHokkaidoOkhotskDescription: '寒流域では、遠くから運ばれた破片や漁具が海鳥や海獣の生活圏に入り込むことがあります。',
    regionHokkaidoOkhotskEvidence: '環境省調査の対象には、漂着ごみ、漂流ごみ、海底ごみが含まれます。',
    regionKyushuWest: '九州西岸',
    regionKyushuWestAmount: '目安：外洋からの漂着と河川流入が重なる沿岸',
    regionKyushuWestImpact: '観光海岸・漁場への漂着',
    regionKyushuWestDescription: '外洋に開いた海岸では、近くの街から出たごみだけでなく、潮流で運ばれたごみも見えやすくなります。',
    regionKyushuWestEvidence: '調査索引は、日本周辺の漂着・漂流・海底ごみの年次資料をたどる入口になります。'
  },
  zh: {
    chartJapanPlasticOutflowTotal: '海洋塑料垃圾总量',
    chartJapanMacroPlastic: '大块塑料垃圾',
    chartJapanUnintentionalMicroplastic: '磨损产生的微塑料',
    chartJapanIntentionalMicroplastic: '产品里添加的微塑料',
    chartJapanTextileFiber: '洗衣产生的纤维',
    chartJapanResinPellet: '树脂颗粒/发泡珠',
    chartJapanDetergentCapsules: '洗涤用品香味胶囊',
    mapTypeUrbanBay: '都市海湾',
    mapTypeSemiClosedSea: '半封闭海域',
    mapTypeDriftCoast: '漂着海岸',
    mapTypeCoral: '珊瑚礁海岸',
    mapTypeFishing: '渔业沿岸',
    mapTypeColdCurrent: '寒流沿岸',
    mapTypeCurrentGate: '洋流入口',
    mapSourceMOE2025: '环境省 FY2025 推计资料',
    mapSourceMOESurvey: '环境省海洋垃圾调查',
    mapSourceOkinawaStudy: '冲绳沿岸微塑料研究',
    regionTokyoBay: '东京湾・关东沿岸',
    regionTokyoBayAmount: '相关量级：日本全国每年约 1.6万-3.1万吨流入海洋',
    regionTokyoBayImpact: '城市排水、道路粉尘、河川输入',
    regionTokyoBayDescription: '人口和道路密集的海湾，雨天更容易把街道粉尘、轮胎磨损颗粒和细碎塑料，经由河川带进海里。',
    regionTokyoBayEvidence: '环境省推计显示，磨损产生的微塑料每年约 1.4万-2万吨，是非常大的来源。',
    regionOsakaBaySeto: '大阪湾・濑户内海',
    regionOsakaBaySetoAmount: '相关量级：大块塑料垃圾每年约 1,300-8,600 吨',
    regionOsakaBaySetoImpact: '半封闭海域滞留、渔业受影响',
    regionOsakaBaySetoDescription: '海湾和内海水体交换较慢，塑料袋、发泡材料、食品包装等更容易停留在岸边和渔场附近。',
    regionOsakaBaySetoEvidence: '官方推计把看得见的大块塑料和变小后的微塑料分开估算，便于理解不同治理难度。',
    regionTsushimaJapanSea: '对马海峡・日本海侧',
    regionTsushimaJapanSeaAmount: '量级提示：漂着垃圾较容易被观察到的海岸带',
    regionTsushimaJapanSeaImpact: '被洋流带来的漂着垃圾',
    regionTsushimaJapanSeaDescription: '沿着对马暖流，饮料瓶、渔具、发泡材料等可能被带到海岸，形成清理压力。',
    regionTsushimaJapanSeaEvidence: '环境省海洋垃圾实态调查长期关注漂着垃圾、漂流垃圾和海底垃圾。',
    regionOkinawaCoral: '冲绳・珊瑚礁沿岸',
    regionOkinawaCoralAmount: '量级提示：研究采样点均检测到微小塑料',
    regionOkinawaCoralImpact: '珊瑚礁和食物链中的微细垃圾',
    regionOkinawaCoralDescription: '即使海水看起来很清澈，肉眼不容易看到的微小塑料也可能进入珊瑚礁生态和小型生物的摄食路径。',
    regionOkinawaCoralEvidence: '冲绳沿岸研究显示，所有测试地点都发现了塑料颗粒，人类活动较高的区域浓度也更高。',
    regionSanrikuFishing: '三陆沿岸',
    regionSanrikuFishingAmount: '相关量级：海域回收部分全国推计每年约 412 吨',
    regionSanrikuFishingImpact: '渔具、绳索造成缠绕',
    regionSanrikuFishingDescription: '复杂的里亚式海岸和渔场里，网具、绳索残片如果留在海里，会增加鱼类、海鸟、海兽被缠住的风险。',
    regionSanrikuFishingEvidence: '环境省资料把海岸、海域、河川等不同回收界面一起纳入海洋垃圾整理。',
    regionHokkaidoOkhotsk: '北海道・鄂霍次克沿岸',
    regionHokkaidoOkhotskAmount: '量级提示：需关注流冰和海流带来的漂着垃圾',
    regionHokkaidoOkhotskImpact: '海鸟、海兽误食和缠绕',
    regionHokkaidoOkhotskDescription: '寒流区域里，被远距离搬运的碎片和渔具可能进入海鸟、海兽的生活范围。',
    regionHokkaidoOkhotskEvidence: '环境省调查对象包含海岸漂着、海面漂流和海底垃圾。',
    regionKyushuWest: '九州西岸',
    regionKyushuWestAmount: '量级提示：外洋漂着与河川输入重叠的沿岸',
    regionKyushuWestImpact: '旅游海岸和渔场受到漂着垃圾影响',
    regionKyushuWestDescription: '面向外洋的海岸，不只会看到附近城市排出的垃圾，也容易看到被潮流搬运来的垃圾。',
    regionKyushuWestEvidence: '环境省调查索引提供日本周边漂着、漂流和海底垃圾年度资料的追溯入口。'
  },
  en: {
    chartJapanPlasticOutflowTotal: 'Marine plastic litter outflow total',
    chartJapanMacroPlastic: 'Large plastic litter',
    chartJapanUnintentionalMicroplastic: 'Wear-generated microplastics',
    chartJapanIntentionalMicroplastic: 'Product-added microplastics',
    chartJapanTextileFiber: 'Laundry textile fibers',
    chartJapanResinPellet: 'Resin pellets and foam beads',
    chartJapanDetergentCapsules: 'Detergent fragrance capsules',
    mapTypeUrbanBay: 'Urban bay',
    mapTypeSemiClosedSea: 'Semi-enclosed sea',
    mapTypeDriftCoast: 'Drift coast',
    mapTypeCoral: 'Coral coast',
    mapTypeFishing: 'Fishing coast',
    mapTypeColdCurrent: 'Cold-current coast',
    mapTypeCurrentGate: 'Current gate',
    mapSourceMOE2025: 'MOE FY2025 estimate',
    mapSourceMOESurvey: 'MOE marine litter survey',
    mapSourceOkinawaStudy: 'Okinawa coastal microplastic study',
    regionTokyoBay: 'Tokyo Bay and Kanto coast',
    regionTokyoBayAmount: 'Related scale: about 16,000-31,000 tons flows to the sea each year nationwide',
    regionTokyoBayImpact: 'Urban runoff, road dust, and river inputs',
    regionTokyoBayDescription: 'Dense roads and population make the bay more exposed to tire wear, road dust, and small plastic fragments carried by rain and rivers.',
    regionTokyoBayEvidence: 'MOE estimates wear-generated microplastics at about 14,000-20,000 tons each year.',
    regionOsakaBaySeto: 'Osaka Bay and Seto Inland Sea',
    regionOsakaBaySetoAmount: 'Related scale: large plastic litter is about 1,300-8,600 tons each year',
    regionOsakaBaySetoImpact: 'Retention in semi-enclosed waters and fishery impact',
    regionOsakaBaySetoDescription: 'Bays and inland seas exchange water slowly, so bags, foam, and packaging can remain near coasts and fishing grounds.',
    regionOsakaBaySetoEvidence: 'Official estimates separate visible large plastics from smaller microplastic sources.',
    regionTsushimaJapanSea: 'Tsushima Strait and Japan Sea coast',
    regionTsushimaJapanSeaAmount: 'Cue: coastal belt where washed-ashore debris is easy to observe',
    regionTsushimaJapanSeaImpact: 'Current-driven washed-ashore debris',
    regionTsushimaJapanSeaDescription: 'The Tsushima Current can carry bottles, fishing gear, and foam toward beaches, increasing cleanup pressure.',
    regionTsushimaJapanSeaEvidence: 'MOE marine litter surveys track washed-ashore, floating, and seabed debris.',
    regionOkinawaCoral: 'Okinawa coral coast',
    regionOkinawaCoralAmount: 'Cue: microplastics detected at all sampled study sites',
    regionOkinawaCoralImpact: 'Fine debris around coral reefs and the food chain',
    regionOkinawaCoralDescription: 'Even clear-looking water can contain small plastics that enter reef habitats and feeding pathways.',
    regionOkinawaCoralEvidence: 'A coastal Okinawa study found plastic particles at all test sites, with higher concentrations in areas of high human activity.',
    regionSanrikuFishing: 'Sanriku coast',
    regionSanrikuFishingAmount: 'Related scale: sea-area recovery is estimated around 412 tons each year nationwide',
    regionSanrikuFishingImpact: 'Entanglement from fishing gear and ropes',
    regionSanrikuFishingDescription: 'In complex ria coasts and fishing grounds, remaining nets and ropes can entangle fish, seabirds, and marine mammals.',
    regionSanrikuFishingEvidence: 'MOE materials organize marine debris across coast, sea-area, and river recovery interfaces.',
    regionHokkaidoOkhotsk: 'Hokkaido Okhotsk coast',
    regionHokkaidoOkhotskAmount: 'Cue: watch for debris moved by currents and sea ice',
    regionHokkaidoOkhotskImpact: 'Ingestion and entanglement for seabirds and marine mammals',
    regionHokkaidoOkhotskDescription: 'Fragments and fishing gear transported over distance can enter habitats used by seabirds and marine mammals.',
    regionHokkaidoOkhotskEvidence: 'MOE surveys include washed-ashore, floating, and seabed litter.',
    regionKyushuWest: 'Western Kyushu coast',
    regionKyushuWestAmount: 'Cue: open-ocean drift and river inputs overlap here',
    regionKyushuWestImpact: 'Washed-ashore debris on tourism coasts and fishing grounds',
    regionKyushuWestDescription: 'Open coasts show both local waste and debris transported by currents from elsewhere.',
    regionKyushuWestEvidence: 'The MOE survey index is an entry point for annual reports on washed-ashore, floating, and seabed debris.'
  }
};

// 当前语言是所有页面脚本共享的运行时状态，由 initLanguageSwitcher 统一初始化。
let currentLanguage = 'ja';

/**
 * 获取本地化标签
 * Get localized label
 * 根据当前语言返回对应的本地化文本
 * Returns localized text based on current language
 * @param {string} key - 标签键 / Label key
 * @returns {string} 本地化文本 / Localized text
 */
function getLocalizedLabel(key) {
  // 页面翻译优先，动态图表/地图标签作为后备，最后返回键名便于发现缺失项。
  return translations[currentLanguage][key] || localizedLabels[currentLanguage][key] || key;
}

/**
 * 格式化模板字符串
 * Format template string
 * 用提供的数值替换模板中的占位符
 * Replaces placeholders in template with provided values
 * @param {string} template - 模板字符串 / Template string
 * @param {object} values - 替换值对象 / Replacement values object
 * @returns {string} 格式化后的字符串 / Formatted string
 */
function formatTemplate(template, values) {
  return template.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? '');
}

/**
 * 更新页面翻译内容
 * Update localized page text
 * 遍历页面中的 data-i18n 属性并替换为当前语言文本
 */
function translatePage() {
  document.documentElement.lang = currentLanguage;
  // 只替换明确声明 data-i18n 的文本，图片 alt 与动态组件由各页面脚本更新。
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (!translations[currentLanguage] || !translations[currentLanguage][key]) return;
    el.textContent = translations[currentLanguage][key];
  });
}

/**
 * 初始化语言切换器
 * Initialize the language selector and load saved语言设置
 */
function initLanguageSwitcher() {
  // 优先使用用户上次选择；首次访问时再根据浏览器语言判断。
  const savedLanguage = localStorage.getItem('marineDebrisLanguage');
  currentLanguage = savedLanguage || (navigator.language.startsWith('zh') ? 'zh' : navigator.language.startsWith('en') ? 'en' : 'ja');

  const languageSelect = document.getElementById('languageSwitch');
  if (languageSelect) {
    languageSelect.value = currentLanguage;
    languageSelect.addEventListener('change', event => {
      currentLanguage = event.target.value;
      localStorage.setItem('marineDebrisLanguage', currentLanguage);
      translatePage();
      // 动态生成的图表、地图、游戏和图片说明通过此钩子自行重绘。
      if (typeof window.onLanguageChanged === 'function') {
        window.onLanguageChanged();
      }
    });
  }

  translatePage();
  if (typeof window.onLanguageChanged === 'function') {
    window.onLanguageChanged();
  }
}

/**
 * 获取权重颜色
 * Get weight color
 * 根据污染程度返回对应的颜色值
 * Returns color value based on pollution level
 * @param {string} weight - 权重级别 ('low', 'medium', 'high') / Weight level
 * @returns {string} CSS颜色值 / CSS color value
 */
function getWeightColor(weight) {
  if (weight === 'high') return 'var(--map-high)';
  if (weight === 'medium') return 'var(--map-medium)';
  return 'var(--map-low)';
}
